version: '3'
services:
  app:
    build: app
    image: anicklaus/leto-web
    ports:
      - "80:80"
    networks:
      - nginx_proxy
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
